stages:
  - test
  - test_master
  - deploy

before_script:
    - source /home/divya/setup.sh
    - export PYTHONPATH=$(pwd)
    - export PYENV_ROOT=/home/divya/.pyenv
    - export PATH=/home/divya/.pyenv/bin:$PATH
    - eval "$(pyenv init -)"
    - eval "$(pyenv init - --path)"
    - eval "$(pyenv virtualenv-init -)"
    - pyenv activate py38
    - pip install pytest
    - pip install pytest-timeout
    - pip uninstall -y aapg
    - python3 setup.py install
test:
    script:
        - source /home/divya/setup.sh
        - export PYTHONPATH=$(pwd)
        - export PYENV_ROOT=/home/divya/.pyenv
        - export PATH=/home/divya/.pyenv/bin:$PATH
        - eval "$(pyenv init -)"
        - eval "$(pyenv init - --path)"
        - eval "$(pyenv virtualenv-init -)"
        - pyenv activate py38
        - pytest tests/test_aapg.py -m "serial" -v
        - pytest tests/test_aapg.py -m "not serial" -v --seed=$((1 + $RANDOM)) -s
    #only:
     #   refs:
      #      - 89-aapg-regression
    tags:
        - aapg_regression

test_master:
    script:
        - source /home/divya/setup.sh
        - export PYTHONPATH=$(pwd)
        - export PYENV_ROOT=/home/divya/.pyenv
        - export PATH=/home/divya/.pyenv/bin:$PATH
        - eval "$(pyenv init -)"
        - eval "$(pyenv init - --path)"
        - eval "$(pyenv virtualenv-init -)"
        - pyenv activate py38
        - pytest tests/test_aapg.py -m "serial" -v
        - pytest tests/test_aapg.py -m "not serial" -v --seed=$((1 + $RANDOM)) -s
   # only:
    #    refs:
     #       - 89-aapg-regression
    tags:
        - aapg_regression

deploy:
    stage: deploy
    script:
        - source /home/divya/setup.sh
        - export PYTHONPATH=$(pwd)
        - export PYENV_ROOT=/home/divya/.pyenv
        - export PATH=/home/divya/.pyenv/bin:$PATH
        - eval "$(pyenv init -)"
        - eval "$(pyenv init - --path)"
        - eval "$(pyenv virtualenv-init -)"
        - pyenv activate py38
        - pip install twine semver
        - python setup.py sdist
        - python -m twine upload --username $shaktipypiusername --password $shaktipypipassword dist/*
        - python /scratch/version-extract-rst.py
   # only:
    #    refs:
     #       - 89-aapg-regression
    tags:
        - aapg_regression

