stages:
  - test
  - test_master
  - deploy

before_script:
    - source /home/divya/setup.sh
    - export PYTHONPATH=$(pwd)
    #- export PATH="/home/divya/.pyenv/bin:$PATH"
   # - eval "$(pyenv init -)"
   # - eval "$(pyenv virtualenv-init -)"
   # - pyenv activate py37
    - export PATH="/usr/local/bin:$PATH"
    - export PYENV_ROOT=/home/divya/.pyenv
    - export PATH=/home/divya/.pyenv/bin:$PATH
    - export PYENV_ROOT=/home/divya/.local
    - export PATH=/home/divya/.local/bin:$PATH
    - eval "$(pyenv init -)"
    - eval "$(pyenv init - --path)"
    - eval "$(pyenv virtualenv-init -)"
    - source /home/divya/.bashrc
   # - export PATH=$PATH:/home/gitlab-runner/.local/bin
    - pyenv activate 
    - exec $SHELL
    - bash

    - pip install pytest
    - pip install pytest-timeout
    - pip uninstall -y aapg
    - python setup.py install
test:
    script:
        - source /home/divya/setup.sh
        - export PYTHONPATH=$(pwd)
        - export PATH="/usr/local/bin:$PATH"
    #- export PATH="/home/divya/.pyenv/bin:$PATH"
        - eval "$(pyenv init -)"
   # - eval "$(pyenv virtualenv-init -)"
   # - pyenv activate py37
        - export PYENV_ROOT=/home/divya/.pyenv
        - export PATH=/home/divya/.pyenv/bin:$PATH
        - export PYENV_ROOT=/home/divya/.local
        - export PATH=/home/divya/.local/bin:$PATH
        - eval "$(pyenv init - --path)"
        - eval "$(pyenv virtualenv-init -)"
        - source /home/divya/.bashrc
   # - export PATH=$PATH:/home/gitlab-runner/.local/bin
        - pyenv activate py38
        - exec $SHELL
        - pytest tests/test_aapg.py -m "serial" -v
        - pytest tests/test_aapg.py -m "not serial" -v --seed=$((1 + $RANDOM)) -s
    only:
        refs:
            - 89-aapg-regression
    tags:
        - aapg_regression

test_master:
    script:
        - source /home/divya/setup.sh
        - export PYTHONPATH=$(pwd)
        - export PATH="/usr/local/bin:$PATH"
    #- export PATH="/home/divya/.pyenv/bin:$PATH"
        - eval "$(pyenv init -)"
   # - eval "$(pyenv virtualenv-init -)"
   # - pyenv activate py37
        - export PYENV_ROOT=/home/divya/.pyenv
        - export PATH=/home/divya/.pyenv/bin:$PATH
        - eval "$(pyenv init - --no-rehash)"
        - eval "$(pyenv virtualenv-init -)"
       # - source /home/divya/.bashrc
        - export PATH=$PATH:/home/gitlab-runner/.local/bin
        - pyenv activate py38
        - exec $SHELL
        - pytest tests/test_aapg.py -m "serial" -v
        - pytest tests/test_aapg.py -m "not serial" -v --seed=$((1 + $RANDOM)) -s
    only:
        refs:
            - 89-aapg-regression
    tags:
        - aapg_regression

deploy:
    stage: deploy
    script:
        - source /home/divya/setup.sh
        - export PYTHONPATH=$(pwd)
        - export PATH="/usr/local/bin:$PATH"
        #- export PATH="/home/divya/.pyenv/bin:$PATH"
        - eval "$(pyenv init -)"
       # - eval "$(pyenv virtualenv-init -)"
       # - pyenv activate py37
        - export PYENV_ROOT=/home/divya/.pyenv
        - export PATH=/home/divya/.pyenv/bin:$PATH
        - eval "$(pyenv init - --no-rehash)"
        - eval "$(pyenv virtualenv-init -)"
      #  - source /home/divya/.bashrc
        #- export PATH=$PATH:/home/gitlab-runner/.local/bin
        - pyenv activate py38
        - exec $SHELL
        - pip install twine semver
        - python setup.py sdist
        - python -m twine upload --username $shaktipypiusername --password $shaktipypipassword dist/*
        - python /scratch/version-extract-rst.py
    only:
        refs:
            - 89-aapg-regression
    tags:
        - aapg_regression

